### ISSUE TITLE
About training the model

### ISSUE THREAD

**Issue by likping** [hatton613/BearLLM#1]
Are vibration signal features and user prompts both turned into word vectors and fed into the large language model for implementation?

**Comment by hatton613** [comment]
Yes. In practice, we deploy an LLM using huggingface's transformers library. We modifies the Embedding layer with the following workflow: 1) convert user prompts to word vectors using the original Embedding layer; 2) convert vibrational signal saved at specified location to word vector using the FCN and alignment layers; and 3) replace the placeholder portion of the prompts word vectors to vibrational signals word vectors. For more details, please stay tuned to our subsequent publicized code.

**Comment by likping** [comment]
Thank you for your answer and look forward to seeing more details
